### PR TITLE
Update the README example to use Makie.

### PR DESCRIPTION
**Pull request by asinghvi17**
This replaces the old GLVisualize example with a Makie one, which I can verify works.

Incidentally, the GLNormalMesh call fails, so I replaced it.
```julia
 msh = GLNormalMesh(vertices=v, faces=triangle_faces)
ERROR: MethodError: no method matching AbstractArray{GeometryBasics.Ngon{Dim,Float32,3,PointMeta{Dim,Float32,Point{Dim,Float32},(:normals,),Tuple{Vec{3,Float32}}}},1} where Dim(; vertices=Point{3,Float32}[[1.2246469f-16, -1.0, 0.0], [-0.099567845, -0.99503076, 0.0], [-0.19814615, -0.9801725, 0.0], [-0.29475516, -0.9555728, 0.0], [-0.3884348, -0.9214762, 0.0], [-0.478254, -0.8782216, 0.0], [-0.56332004, -0.82623875, 0.0], [-0.64278764, -0.76604444, 0.0], [-0.71586686, -0.6982368, 0.0], [-0.7818315, -0.6234898, 0.0]  …  [0.39091575, -0.3117449, 0.0], [0.35793343, -0.3491184, 0.0], [0.32139382, -0.38302222, 0.0], [0.28166002, -0.41311938, 0.0], [0.239127, -0.4391108, 0.0], [0.1942174, -0.4607381, 0.0], [0.14737758, -0.4777864, 0.0], [0.099073075, -0.49008626, 0.0], [0.049783923, -0.49751538, 0.0], [1.8369701f-16, -0.5, 0.0]], faces=NgonFace{3,OffsetInteger{-1,UInt32}}[TriangleFace(OffsetInteger{-1,UInt32}(0x00000000), OffsetInteger{-1,UInt32}(0x0000003f), OffsetInteger{-1,UInt32}(0x0000003e)), TriangleFace(OffsetInteger{-1,UInt32}(0x0000003e), OffsetInteger{-1,UInt32}(0x0000003d), OffsetInteger{-1,UInt32}(0x0000003c)), TriangleFace(OffsetInteger{-1,UInt32}(0x0000003c), OffsetInteger{-1,UInt32}(0x0000003b), OffsetInteger{-1,UInt32}(0x0000003a)), TriangleFace(OffsetInteger{-1,UInt32}(0x0000003a), OffsetInteger{-1,UInt32}(0x00000039), OffsetInteger{-1,UInt32}(0x00000038)), TriangleFace(OffsetInteger{-1,UInt32}(0x00000038), OffsetInteger{-1,UInt32}(0x00000037), OffsetInteger{-1,UInt32}(0x00000036)), TriangleFace(OffsetInteger{-1,UInt32}(0x00000036), OffsetInteger{-1,UInt32}(0x00000035), OffsetInteger{-1,UInt32}(0x00000034)), TriangleFace(OffsetInteger{-1,UInt32}(0x00000034), OffsetInteger{-1,UInt32}(0x00000033), OffsetInteger{-1,UInt32}(0x00000032)), TriangleFace(OffsetInteger{-1,UInt32}(0x00000032), OffsetInteger{-1,UInt32}(0x00000031), OffsetInteger{-1,UInt32}(0x00000030)), TriangleFace(OffsetInteger{-1,UInt32}(0x00000030), OffsetInteger{-1,UInt32}(0x0000002f), OffsetInteger{-1,UInt32}(0x0000002e)), TriangleFace(OffsetInteger{-1,UInt32}(0x0000002e), OffsetInteger{-1,UInt32}(0x0000002d), OffsetInteger{-1,UInt32}(0x0000002c))  …  TriangleFace(OffsetInteger{-1,UInt32}(0x00000030), OffsetInteger{-1,UInt32}(0x0000006b), OffsetInteger{-1,UInt32}(0x0000006c)), TriangleFace(OffsetInteger{-1,UInt32}(0x00000074), OffsetInteger{-1,UInt32}(0x00000000), OffsetInteger{-1,UInt32}(0x00000030)), TriangleFace(OffsetInteger{-1,UInt32}(0x00000030), OffsetInteger{-1,UInt32}(0x0000006c), OffsetInteger{-1,UInt32}(0x0000006d)), TriangleFace(OffsetInteger{-1,UInt32}(0x00000073), OffsetInteger{-1,UInt32}(0x00000074), OffsetInteger{-1,UInt32}(0x00000030)), TriangleFace(OffsetInteger{-1,UInt32}(0x00000030), OffsetInteger{-1,UInt32}(0x0000006d), OffsetInteger{-1,UInt32}(0x0000006e)), TriangleFace(OffsetInteger{-1,UInt32}(0x00000072), OffsetInteger{-1,UInt32}(0x00000073), OffsetInteger{-1,UInt32}(0x00000030)), TriangleFace(OffsetInteger{-1,UInt32}(0x00000030), OffsetInteger{-1,UInt32}(0x0000006e), OffsetInteger{-1,UInt32}(0x0000006f)), TriangleFace(OffsetInteger{-1,UInt32}(0x00000071), OffsetInteger{-1,UInt32}(0x00000072), OffsetInteger{-1,UInt32}(0x00000030)), TriangleFace(OffsetInteger{-1,UInt32}(0x00000030), OffsetInteger{-1,UInt32}(0x0000006f), OffsetInteger{-1,UInt32}(0x00000070)), TriangleFace(OffsetInteger{-1,UInt32}(0x00000070), OffsetInteger{-1,UInt32}(0x00000071), OffsetInteger{-1,UInt32}(0x00000030))])
Stacktrace:
    Function         Module  Signature
    ────────         ──────  ─────────
[1] top-level scope
REPL[13]:1
```

### CODE REVIEW

**Comment by SimonDanisch** [comment]
I fixed the constructor!

**Comment by SimonDanisch** [comment]
Thanks :)

**Comment by asinghvi17** [comment]
Nice to know I don't have to bother with `GLNormalUVMesh` anymore :)

**Comment by SimonDanisch** [comment]
Yup! This is all gone for the better ( I think :D)

**Pull request merged**
